vim.g.mapleader = " "
vim.g.maplocalleadher = " "

vim.keymap.set({ "v", "n" }, "$", "g_")
vim.keymap.set({ "v", "n" }, "g_", "$")

vim.keymap.set({'n','t'}, '<A-d>', '<cmd>Lspsaga term_toggle<CR>')
vim.keymap.set("n", "<leader><CR>", "<CMD>noh<CR>", { desc = "Clear Highlights" })
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>", { silent = true, desc = "Close Terminal" })
vim.keymap.set("t", "<M-h>", "<C-\\><C-n><C-w>h",{desc = "Move window"})
vim.keymap.set("t", "<M-j>", "<C-\\><C-n><C-w>j",{desc = "Move window"})
vim.keymap.set("t", "<M-k>", "<C-\\><C-n><C-w>k",{desc = "Move window"})
vim.keymap.set("t", "<M-l>", "<C-\\><C-n><C-w>l",{desc = "Move window"})
vim.keymap.set("n", "<M-h>", "<C-w>h",{desc = "Move window"})
vim.keymap.set("n", "<M-j>", "<C-w>j",{desc = "Move window"})
vim.keymap.set("n", "<M-k>", "<C-w>k",{desc = "Move window"})
vim.keymap.set("n", "<M-l>", "<C-w>l",{desc = "Move window"})
--vim.keymap.set({"n","v"},"<C-j>", "5j", { noremap = true, silent = true })
--vim.keymap.set({"n","v"},"<C-k>", "5k", { noremap = true, silent = true })
vim.keymap.set({ "n", "i", "v" }, "<Left>", "<Nop>")
vim.keymap.set({ "n", "i", "v" }, "<Right>", "<Nop>")
vim.keymap.set({ "n", "i", "v" }, "<Up>", "<Nop>")
vim.keymap.set({ "n", "i", "v" }, "<Down>", "<Nop>")
vim.o.mouse = ""

vim.keymap.set("x", "<leader>p", '"_dP')
vim.keymap.set("n", "<leader>cl", '<cmd>cclose<CR>')
vim.keymap.set("n", "<leader>co", '<cmd>copen<CR>')

vim.keymap.set("n", "]b", "<cmd>bnext<CR>", { silent = true })
vim.keymap.set("n", "[b", "<cmd>bprevious<CR>", { silent = true })
vim.keymap.set("n", "]B", "<cmd>blast<CR>", { silent = true })
vim.keymap.set("n", "[B", "<cmd>bfirst<CR>", { silent = true })
vim.keymap.set("n", "]q", "<cmd>cnext<CR>", { silent = true })
vim.keymap.set("n", "[q", "<cmd>cprevious<CR>", { silent = true })
vim.keymap.set("n", "]Q", "<cmd>clast<CR>", { silent = true })
vim.keymap.set("n", "[Q", "<cmd>cfirst<CR>", { silent = true })
vim.keymap.set("n", "]<C-q>", "<cmd>cnfile<CR>", { silent = true })
vim.keymap.set("n", "[<C-q>", "<cmd>cpfile<CR>", { silent = true })
vim.keymap.set("n", "]a", "<cmd>next<CR>", { silent = true })
vim.keymap.set("n", "[a", "<cmd>previous<CR>", { silent = true })
vim.keymap.set("n", "]A", "<cmd>last<CR>", { silent = true })
vim.keymap.set("n", "[A", "<cmd>first<CR>", { silent = true })
vim.keymap.set("n", "]l", "<cmd>lnext<CR>", { silent = true })
vim.keymap.set("n", "[l", "<cmd>lprevious<CR>", { silent = true })
vim.keymap.set("n", "]L", "<cmd>llast<CR>", { silent = true })
vim.keymap.set("n", "[L", "<cmd>lfirst<CR>", { silent = true })
vim.keymap.set("n", "]<C-l>", "<cmd>lnfile<CR>", { silent = true })
vim.keymap.set("n", "[<C-l>", "<cmd>lpfile<CR>", { silent = true })

